-- liquibase formatted sql

-- change_set aleksey:1

create table feeds
(
    id                bigint      generated by default as identity primary key,
    title             TEXT        NOT NULL,
    content           TEXT        NOT NULL,
    date_time         timestamp   NOT NULL,
    category_id       VARCHAR(20) NOT NULL -- enum NewsCategory
);

create table categories
(
    id                  bigint      generated by default as identity primary key,
    news_category       VARCHAR(20) NOT NULL -- enum NewsCategory
);
