-- liquibase formatted sql

-- changeset aleksey:1

-- table categories (Category)
CREATE TABLE categories
(
    id            bigint generated by default as identity primary key,
    news_category VARCHAR(20) UNIQUE NOT NULL
);

-- table feeds (Feed)
CREATE TABLE feeds
(
    id          bigint generated by default as identity primary key,
    title       TEXT      NOT NULL,
    content     TEXT      NOT NULL,
    date_time   timestamp NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories (id)
);

